### PR TITLE
NetlifyCMS: Add /funktionen

### LINKED ISSUE #41: Allow editing pages under /funktionen/ via Netflify
Not sure if this is possible with reasonable effort, but it would be great if it were possible to edit (or even create!) pages under `/funktionen/`. I guess what we'd need are two fairly complex widgets, one for the "hero" section at the top and then one for the subsequent sections with the boxes and horizontal image slider (or maybe the hero section can be "static" and the title, subtitle etc, can be provided via the front matter, since it only appears once) . @BrunoBernardino Do you think that's possible?

### PR DESCRIPTION
**Pull request by BrunoBernardino**
This is still very WIP. The sections show but not all fields or everything is working.

Still needs to allow editing the full `sections` and then have a better preview.

I also noticed the sections/waterfall template hasn't been migrated to nunjucks and was being ignored, so I'll also fix that.

Fixes #41

### CODE REVIEW

**Comment by BrunoBernardino** [comment]
FYI @MaKleSoft / @Lorenz147 At this point I'm only missing adding the admin preview for the `/funktionen/*` section, which I expect will take 4-8h (I'm currently "at time" for September, including the 3.5h overtime from August).

**Comment by BrunoBernardino** [comment]
@MaKleSoft / @Lorenz147 I know you haven't approved it yet, but I finished it anyway. Took me 4 hours. (with the 2h of fixing the figure regexp/recognition yesterday, I'm at 6h overtime, including the 3.5 of August).

**Comment by MaKleSoft** [comment]
@BrunoBernardino Are the previews for the "slides" template supposed to work yet? Because the alignment of the screenshots and the hover effects on the tiles don't seem to be working properly yet.

**Comment by BrunoBernardino** [comment]
The previews for the slides should be working, simply without animations/clicks (I'm not loading that specific JavaScript). Are you not seeing that? Can you show me a screenshot, because I am.

**Comment by MaKleSoft** [comment]
Screenshot 2022-09-25 at 17 00 01
I guess we don't need to replicate the exact behavior in the preview but it would be nice to see all the screenshots and read the full text of the tiles. Maybe you can remove the 3d transform and just make the screenshots scrollable horizontally?

**Comment by BrunoBernardino** [comment]
You should be able to scroll them horizontally already (I am able to, at least), but I can change the 3d transform, sure.

**Comment by MaKleSoft** [comment]
Yeah, I can confirm that they're scrollable. So maybe just remove the 3d transform and add back the scrollbar.

**Comment by BrunoBernardino** [comment]
Alright, check it out now.

**Comment by MaKleSoft** [comment]
The previous version worked better, actually 😅 I doesn't have to be pretty, but at a minimum all screenshots should be clearly visible and the text readable. I don't think it's worth putting much more effort into this though. I'd say let's reverse the last change and merge this.

Screenshot 2022-09-26 at 15 06 02

**Pull request merged**
